import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { existsSync, mkdirSync, readFileSync, readdirSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PassThrough } from "node:stream";
import test from "node:test";
import { buildNovelPackage } from "../src/novel-play/canon.ts";
import { novelNodeId, prepareNovelSource } from "../src/novel-play/source.ts";
import { saveNovelPackage } from "../src/novel-play/store.ts";
import { saveStageSkill } from "../src/stage/skill-store.ts";
import { NOVEL_PLAY_LIMITS, handleNovelPlayApiRequest, novelPlayCounters } from "../server/novel-play-api.ts";
import type { RestHost } from "../server/rest.ts";

const proposal = JSON.stringify({ time:{text:"晨钟响起",quote:"晨钟响起"}, place:{text:"城门",quote:"城门"}, sceneText:{text:"晨钟响起",quote:"晨钟响起"}, openingNarration:{text:"旅人推开城门",quote:"旅人推开城门"}, publicCharacterProfiles:[], publicWorldFacts:[] });
function deferred<T>() { let resolve!:(v:T)=>void, reject!:(e?:unknown)=>void; const promise=new Promise<T>((y,n)=>{resolve=y;reject=n}); return {promise,resolve,reject}; }
const root=()=>join(tmpdir(),`liyuan-novel-adversarial-${Date.now()}-${Math.random().toString(16).slice(2)}`);
function skill(cwd:string,dir:string,body:string){ saveStageSkill(cwd,{dir,name:dir,description:"adversarial fixture",resident:false,everyBeat:false,body}); }
function corpus(cwd:string){
 const docId="doc-safe-id", text="第一章\n晨钟响起。旅人推开城门。", dir=join(cwd,".liyuan","outline","research","corpus"); mkdirSync(join(dir,"texts"),{recursive:true});
 writeFileSync(join(dir,"documents.json"),JSON.stringify([{id:docId,title:"测试小说",sourceKind:"upload",originalName:"novel.txt",chars:text.length,encoding:"utf-8",chapterCount:1,chunkCount:1,status:"ready",cardKey:"card",createdAt:new Date(0).toISOString(),updatedAt:new Date(0).toISOString()}])); writeFileSync(join(dir,"texts",`${docId}.txt`),text);
 const source=prepareNovelSource({id:docId,title:"测试小说",status:"ready",chars:text.length,chunkCount:1},text), quote="。", start=text.lastIndexOf(quote), ref={chunkIndex:0,start,end:start+quote.length,quote};
 const pkg=buildNovelPackage(source,[{id:"chapter-0",order:0,title:"第一章"}],[{id:novelNodeId(source,ref,"bell"),key:"bell",stageId:"chapter-0",order:0,title:"晨钟",summary:"晨钟响起",visibility:"public",dependsOn:[],sourceRefs:[ref]}]); saveNovelPackage(cwd,source,pkg); return {docId,text,revision:pkg.revision,nodeId:pkg.nodes[0].id};
}
const defaultCard="assets/cards/default_Qingwu.json";
function cardAndConfig(cwd:string){ mkdirSync(join(cwd,"assets","cards"),{recursive:true}); writeFileSync(join(cwd,defaultCard),JSON.stringify({spec:"chara_card_v2",spec_version:"2.0",data:{name:"normal",description:"",personality:"",scenario:"",first_mes:"",mes_example:"",system_prompt:"",post_history_instructions:"",creator_notes:"",alternate_greetings:[],tags:[]}})); writeFileSync(join(cwd,"liyuan.config.json"),JSON.stringify({card:defaultCard,userName:"old",userPersona:"",language:"zh-CN",scanDepth:6,maxLoreInjections:5})); }
function prepare(cwd:string){const d=corpus(cwd);skill(cwd,"小说事件构建","extract exact events");skill(cwd,"小说开场提取","opening extraction");skill(cwd,"小说开演边界","boundary");cardAndConfig(cwd);return d;}
class Request extends PassThrough { method:string;url:string;constructor(method:string,url:string){super();this.method=method;this.url=url} send(v?:unknown){if(v!==undefined)this.write(JSON.stringify(v));this.end()} }
class Response extends EventEmitter {statusCode=0;headers:Record<string,string>={};text="";writableEnded=false;destroyed=false;writeHead(c:number,h:Record<string,string>){this.statusCode=c;this.headers=h}end(v=""){this.text+=v;this.writableEnded=true}json(){return JSON.parse(this.text)}}
function makeHost(cwd:string,runSideText:RestHost["runSideText"],overrides:Partial<RestHost>={}){let sessionId="session-a",runtimeCard=defaultCard;return {cwd,isStreaming:()=>false,runSideText,memoryScope:()=>({sessionId,card:runtimeCard}),switchToCard:async()=>{runtimeCard=JSON.parse(readFileSync(join(cwd,"liyuan.config.json"),"utf8")).card;sessionId="created-session";return "created"},...overrides} as RestHost}
async function request(host:RestHost,method:string,url:string,payload?:unknown){const req=new Request(method,url),res=new Response(),handled=handleNovelPlayApiRequest(req as never,res as never,host);req.send(payload);assert.equal(await handled,true);return {status:res.statusCode,body:res.json(),req,res}}
const preview=(host:RestHost,input:ReturnType<typeof prepare>)=>request(host,"POST","/api/novel-play/preview",{docId:input.docId,revision:input.revision,nodeId:input.nodeId,position:"before",player:{name:"阿岚",identity:"异乡旅人"}});
async function waitFor(check:()=>boolean){for(let i=0;i<100&&!check();i++)await new Promise<void>(r=>setImmediate(r));assert.ok(check(),"condition was not reached")}

// Existing adversarial regressions.
test("same preview token cannot be consumed twice while concurrent request bodies are still arriving",async()=>{const cwd=root(),input=prepare(cwd),gate=deferred<"created">();let switches=0;const host=makeHost(cwd,async()=>proposal,{switchToCard:async()=>{switches++;return gate.promise}}),made=await preview(host,input),token=made.body.preview.token,a=new Request("POST","/api/novel-play/start"),b=new Request("POST","/api/novel-play/start"),ar=new Response(),br=new Response(),ap=handleNovelPlayApiRequest(a as never,ar as never,host),bp=handleNovelPlayApiRequest(b as never,br as never,host);a.write(`{"previewToken":"${token}"`);b.write(`{"previewToken":"${token}"`);a.end("}");b.end("}");await waitFor(()=>switches===1&&(ar.statusCode===409||br.statusCode===409));gate.resolve("created");await Promise.all([ap,bp]);assert.deepEqual([ar.statusCode,br.statusCode].sort(),[201,409]);assert.equal(switches,1)});
test("cancelling a build remains final when the model ignores abort and resolves later",async()=>{const cwd=root(),input=prepare(cwd),model=deferred<string>(),host=makeHost(cwd,async()=>model.promise),made=await request(host,"POST","/api/novel-play/build",{docId:input.docId}),id=made.body.job.id;await waitFor(()=>novelPlayCounters(host).buildOperations===1);assert.equal((await request(host,"DELETE",`/api/novel-play/status/${id}`)).body.job.status,"cancelled");model.resolve(JSON.stringify({nodes:[{key:"bell",title:"晨钟",summary:"晨钟响起",visibility:"public",dependsOn:[],quote:"晨钟响起"}]}));await waitFor(()=>novelPlayCounters(host).buildOperations===0);const status=await request(host,"GET",`/api/novel-play/status/${id}`);assert.equal(status.body.job.status,"cancelled");assert.equal("result" in status.body.job,false)});
test("preview rejects a stale session when binding changes before the model returns",async()=>{const cwd=root(),input=prepare(cwd),model=deferred<string>();let sessionId="session-a";const host=makeHost(cwd,async()=>model.promise,{memoryScope:()=>({sessionId,card:defaultCard})}),pending=preview(host,input);await waitFor(()=>novelPlayCounters(host).previewOperations===1);sessionId="session-b";model.resolve(proposal);const result=await pending;assert.equal(result.status,409);assert.equal(novelPlayCounters(host).previews,0)});
test("preview capacity rejects excess work before invoking a third model",async()=>{const cwd=root(),input=prepare(cwd),g=[deferred<string>(),deferred<string>()];let calls=0;const host=makeHost(cwd,async()=>g[calls++].promise),one=preview(host,input),two=preview(host,input);await waitFor(()=>calls===2);const excess=await preview(host,input);assert.equal(excess.status,429);assert.equal(calls,2);g[0].resolve(proposal);g[1].resolve(proposal);assert.deepEqual((await Promise.all([one,two])).map(v=>v.status),[200,200])});
test("preview deadline returns without waiting for a model that ignores abort",async t=>{t.mock.timers.enable({apis:["setTimeout"]});const cwd=root(),input=prepare(cwd),never=deferred<string>(),host=makeHost(cwd,async()=>never.promise),pending=preview(host,input);await waitFor(()=>novelPlayCounters(host).previewOperations===1);t.mock.timers.tick(NOVEL_PLAY_LIMITS.previewDeadlineMs);assert.equal((await pending).status,504);never.resolve(proposal);await Promise.resolve()});
test("an external config write during a failed switch is neither overwritten nor deleted",async()=>{const cwd=root(),input=prepare(cwd),external=`${JSON.stringify({card:"assets/cards/external.json",userName:"external",marker:"keep"},null,"\t")}\n`,host=makeHost(cwd,async()=>proposal,{switchToCard:async()=>{writeFileSync(join(cwd,"liyuan.config.json"),external);throw new Error("post-side-effect switch failure")}}),made=await preview(host,input),started=await request(host,"POST","/api/novel-play/start",{previewToken:made.body.preview.token});assert.equal(started.status,202);assert.equal(started.body.started.session,"recovery-required");assert.equal(readFileSync(join(cwd,"liyuan.config.json"),"utf8"),external);const generated=readdirSync(join(cwd,"assets","cards")).filter(n=>n.startsWith("novel-play-")&&n.endsWith(".json"));assert.equal(generated.length,1);assert.equal(existsSync(join(cwd,"assets","cards",generated[0])),true)});
test("corpus reads reject a symlink that escapes the corpus text directory",async()=>{const cwd=root(),input=prepare(cwd),external=join(cwd,"outside.txt"),textFile=join(cwd,".liyuan","outline","research","corpus","texts",`${input.docId}.txt`);writeFileSync(external,input.text);unlinkSync(textFile);symlinkSync(external,textFile);const host=makeHost(cwd,async()=>{throw new Error("model must not run")}),result=await request(host,"POST","/api/novel-play/build",{docId:input.docId});assert.equal(result.status,400);assert.equal(novelPlayCounters(host).buildOperations,0)});

// Latest start hardening regressions.
async function twoPreviews(host:RestHost,input:ReturnType<typeof prepare>){return [await preview(host,input),await preview(host,input)]}
test("start deadline returns recovery-required, denies another start, and matching late settle unlocks",async t=>{t.mock.timers.enable({apis:["setTimeout"]});const cwd=root(),input=prepare(cwd),gate=deferred<"created">();let runtimeCard=defaultCard,prepared="";const host=makeHost(cwd,async()=>proposal,{memoryScope:()=>({sessionId:"session-a",card:runtimeCard}),switchToCard:async()=>{prepared=JSON.parse(readFileSync(join(cwd,"liyuan.config.json"),"utf8")).card;const value=await gate.promise;runtimeCard=prepared;return value}}),[a,b]=await twoPreviews(host,input),pending=request(host,"POST","/api/novel-play/start",{previewToken:a.body.preview.token});await waitFor(()=>novelPlayCounters(host).starting);t.mock.timers.tick(NOVEL_PLAY_LIMITS.startSwitchDeadlineMs);const timed=await pending;assert.equal(timed.status,202);assert.equal(timed.body.started.session,"recovery-required");assert.equal((await request(host,"POST","/api/novel-play/start",{previewToken:b.body.preview.token})).status,409);gate.resolve("created");await waitFor(()=>!novelPlayCounters(host).starting);assert.equal(novelPlayCounters(host).recovery,undefined)});
test("late start settle with runtime/config mismatch keeps recovery lock and denies subsequent starts",async t=>{t.mock.timers.enable({apis:["setTimeout"]});const cwd=root(),input=prepare(cwd),gate=deferred<"created">();let runtimeCard=defaultCard;const host=makeHost(cwd,async()=>proposal,{memoryScope:()=>({sessionId:"session-a",card:runtimeCard}),switchToCard:async()=>gate.promise}),[a,b]=await twoPreviews(host,input),pending=request(host,"POST","/api/novel-play/start",{previewToken:a.body.preview.token});await waitFor(()=>novelPlayCounters(host).starting);t.mock.timers.tick(NOVEL_PLAY_LIMITS.startSwitchDeadlineMs);assert.equal((await pending).body.started.session,"recovery-required");gate.resolve("created");await waitFor(()=>novelPlayCounters(host).recovery!==undefined);assert.equal(novelPlayCounters(host).starting,true);assert.equal((await request(host,"POST","/api/novel-play/start",{previewToken:b.body.preview.token})).status,409)});
test("runtime and config card mismatch rejects preview and rejects start before side effects",async()=>{const cwd=root(),input=prepare(cwd);let runtimeCard="assets/cards/other.json";const host=makeHost(cwd,async()=>proposal,{memoryScope:()=>({sessionId:"session-a",card:runtimeCard})});assert.equal((await preview(host,input)).status,400);runtimeCard=defaultCard;const made=await preview(host,input);runtimeCard="assets/cards/other.json";assert.equal((await request(host,"POST","/api/novel-play/start",{previewToken:made.body.preview.token})).status,400);assert.equal(readdirSync(join(cwd,"assets","cards")).filter(n=>n.startsWith("novel-play-")).length,0)});
test("closing preview response aborts the model and never creates a preview token",async()=>{const cwd=root(),input=prepare(cwd),model=deferred<string>();let signal:AbortSignal|undefined;const host=makeHost(cwd,async(_s,_p,_u,o)=>{signal=o?.signal;return model.promise}),req=new Request("POST","/api/novel-play/preview"),res=new Response(),pending=handleNovelPlayApiRequest(req as never,res as never,host);req.send({docId:input.docId,revision:input.revision,nodeId:input.nodeId,position:"before",player:{name:"阿岚",identity:"异乡旅人"}});await waitFor(()=>novelPlayCounters(host).previewOperations===1);res.destroyed=true;res.emit("close");await waitFor(()=>signal?.aborted===true);model.resolve(proposal);await pending;await waitFor(()=>novelPlayCounters(host).previewOperations===0);assert.equal(novelPlayCounters(host).previews,0);assert.equal(res.text,"")});
test("preview rate limit permits six bounded requests per minute and rejects the seventh",async()=>{const cwd=root(),input=prepare(cwd);let calls=0;const host=makeHost(cwd,async()=>{calls++;return proposal});const statuses=[];for(let i=0;i<NOVEL_PLAY_LIMITS.previewRequestsPerMinute+1;i++)statuses.push((await preview(host,input)).status);assert.deepEqual(statuses,[200,200,200,200,200,200,429]);assert.equal(calls,NOVEL_PLAY_LIMITS.previewRequestsPerMinute)});
