import { useState, type Dispatch, type RefObject, type SetStateAction } from "react";
import { ConfirmButton } from "../../components/kit.tsx";
import { NovelPlayDialog } from "../novel-play.tsx";
import type { CorpusArcDigest, CorpusDetailResponse, CorpusDigest, CorpusDocument, CorpusWorkbenchResponse, NarrativeAsset } from "../types.ts";
function list<T>(value: T[] | undefined | null): T[] { return Array.isArray(value) ? value : []; }
const CORPUS_STATUS: Record<string, string> = { pending: "排队中", cleaning: "清洗中", mapping: "分块摘要", reducing: "弧线归并", extracting: "提炼套路", ready: "已完成", failed: "失败", paused: "已暂停" };
function corpusMeta(doc: CorpusDocument): string { const size = doc.chars > 10000 ? `${Math.round(doc.chars / 10000) / 100}万字` : `${doc.chars}字`; return `${size} · ${doc.chunkCount}块 · ${CORPUS_STATUS[doc.status] ?? doc.status}`; }
function CorpusDigestCard({ detail }: { doc: CorpusDocument; detail: CorpusDetailResponse | undefined }) { const digest: CorpusDigest | undefined = detail?.digest ?? undefined; if (!digest) return <div className="planning-empty">该文档尚未完成消化，暂时没有可展示的梗概。</div>; return <div className="planning-digest">
<section><h3>全书梗概</h3><p>{digest.synopsis}</p></section><div className="planning-section-head"><h3 className="planning-section-title">结构</h3><span>{digest.extractedCount} 条套路 · {(digest.dailyPatterns ?? []).length} 张日常卡 · {(digest.assets ?? []).length} 个素材零件</span></div><div className="planning-grid">{([["主线事件链", digest.structure.plotSpine], ["人物弧线", digest.structure.characterArcs], ["钩子与节奏", digest.structure.hooksAndPacing]] as Array<[string, string]>).map(([label, text]) => <article className="planning-research-card" key={label}><h4>{label}</h4><p>{text || "（未提炼）"}</p></article>)}</div>
{(digest.dailyPatterns ?? []).length > 0 && <section><h3 className="planning-section-title">日常剧情卡</h3><div className="planning-grid">{digest.dailyPatterns!.map((pattern) => <article className="planning-research-card" key={`${pattern.title}-${pattern.locator}`}><h4>{pattern.title}</h4><p><b>活动：</b>{pattern.surfaceActivity}</p><p><b>发起与甜点：</b>{pattern.initiative} / {pattern.sweetBeat}</p><p><b>摩擦与误会：</b>{pattern.friction} / {pattern.misunderstanding}</p><p><b>关系微变：</b>{pattern.microChange}</p><small>停点：{pattern.naturalStop} · 边界：{pattern.escalationLimit}</small></article>)}</div></section>}
{(digest.assets ?? []).length > 0 && <section><h3 className="planning-section-title">可调度素材</h3><div className="planning-grid">{digest.assets!.map((asset: NarrativeAsset, index) => <article className="planning-research-card" key={`${asset.kind}-${asset.title}-${index}`}><div className="planning-card-head"><strong>{asset.title}</strong><span>{asset.kind}</span></div><p>{asset.mechanism}</p><p><b>适用：</b>{asset.appliesWhen}</p><p><b>起手：</b>{asset.opening}</p>{asset.progression.length > 0 && <ol>{asset.progression.map((step) => <li key={step}>{step}</li>)}</ol>}<p><b>转折：</b>{asset.turn} · <b>停点：</b>{asset.stopPoint}</p><small>关系阶段：{asset.relationshipStage || "未标注"} · 压力：{asset.pressure || "未标注"} · 体验：{asset.desiredExperience || "未标注"}</small></article>)}</div></section>}
<section><h3 className="planning-section-title">弧线摘要</h3>{list(digest.arcs).map((arc: CorpusArcDigest) => <details key={arc.title} className="planning-arc"><summary>{arc.title}<span>块 {arc.chunkRange[0] + 1}–{arc.chunkRange[1] + 1}</span></summary><p>{arc.summary}</p></details>)}<div className="planning-page-note">块摘要保留为研究证据；结构化素材会按创作对谈的讨论模式和当前问题择取，不会整包注入大纲模型。</div></section></div>; }
export interface CorpusModuleProps { corpusUploading: boolean; busy: boolean; discoverCorpusWorks: () => void; corpusFileRef: RefObject<HTMLInputElement | null>; uploadCorpusFile: (file: File) => void; corpusUrl: string; setCorpusUrl: Dispatch<SetStateAction<string>>; importCorpusUrl: () => void; corpusLoading: boolean; corpusError: string; corpus: CorpusWorkbenchResponse | null; corpusDetail: Record<string, CorpusDetailResponse>; toggleCorpusDetail: (doc: CorpusDocument) => void; corpusAction: (doc: CorpusDocument, kind: "pause" | "resume" | "delete") => void; }
export function CorpusModule(props: CorpusModuleProps) { const { corpusUploading, busy, discoverCorpusWorks, corpusFileRef, uploadCorpusFile, corpusUrl, setCorpusUrl, importCorpusUrl, corpusLoading, corpusError, corpus, corpusDetail, toggleCorpusDetail, corpusAction } = props; const [playing, setPlaying] = useState<CorpusDocument | null>(null); return <div className="planning-page planning-corpus"><div className="planning-page-note"><strong>藏书消化 · 后台处理。</strong>上传 txt/epub 小说后，系统在后台分块摘要成「剧情梗概 + 结构 + 弧线 + 可复用套路」，产物进入创作素材库供大纲模型参考。请仅上传你有权使用的文本。正文只发往你选择的小说消化模型，不进入台上剧情。</div>
<div className="planning-corpus-actions"><button className="drawer-btn primary" disabled={corpusUploading || busy} onClick={() => void discoverCorpusWorks()}>{corpusUploading ? "正在选书…" : "自动选取 3 部小说"}</button><span>从配置的题材关键词中搜索新作品，自动去重并开始分析。</span></div><div className="planning-research-refresh"><button className="drawer-btn" disabled={corpusUploading || busy} onClick={() => corpusFileRef.current?.click()}>上传 txt/epub</button><input ref={corpusFileRef} type="file" hidden accept=".txt,.epub,text/plain" onChange={(e) => { const f = e.target.files?.[0]; if (f) void uploadCorpusFile(f); }} /><input className="planning-input" value={corpusUrl} onChange={(e) => setCorpusUrl(e.target.value)} placeholder="Kakuyomu 公开作品 URL" /><button className="drawer-btn" disabled={corpusUploading || busy || !corpusUrl.trim()} onClick={() => void importCorpusUrl()}>抓取指定作品</button><span>{corpusLoading ? "同步中…" : "5 秒自动刷新"}</span></div>
{corpusError && <div className="panel-error planning-error">{corpusError}</div>}{!corpusLoading && !corpus && <div className="planning-empty">正在读取藏书消化任务…</div>}{corpus && list(corpus.documents).length === 0 && <div className="planning-empty">还没有上传过小说。txt / epub 会在后台自动分块消化。</div>}{corpus?.running?.map((job) => <div className="planning-warning" key={job.docId}>正在消化：{corpus.documents.find((d) => d.id === job.docId)?.title ?? job.docId} · {CORPUS_STATUS[job.step] ?? job.step} {job.done}/{job.total}</div>)}
{list(corpus?.documents).map((doc) => { const running = corpus?.running?.some((job) => job.docId === doc.id); const detail = corpusDetail[doc.id]; return <article className="planning-proposal planning-corpus-item" key={doc.id}><header><div><span>{doc.status === "ready" ? "DOCUMENT · READY" : `DOCUMENT · ${CORPUS_STATUS[doc.status] ?? doc.status}`}</span><h3>{doc.title}</h3></div><b>{corpusMeta(doc)}{doc.error ? ` · ${doc.error}` : ""}</b></header><div className="planning-corpus-acts">
{doc.status === "ready" && <><button className="drawer-btn primary" disabled={busy} onClick={() => setPlaying(doc)}>从这本小说开演</button><button className="drawer-btn" disabled={busy} onClick={() => void toggleCorpusDetail(doc)}>{detail ? "收起" : "梗概▾"}</button></>}{doc.status === "failed" && <button className="drawer-btn" disabled={busy} onClick={() => void corpusAction(doc, "resume")}>重试</button>}{doc.status === "paused" && <button className="drawer-btn" disabled={busy} onClick={() => void corpusAction(doc, "resume")}>续跑</button>}{(doc.status === "mapping" || doc.status === "cleaning" || running) && doc.status !== "paused" && <button className="drawer-btn" disabled={busy} onClick={() => void corpusAction(doc, "pause")}>暂停</button>}<ConfirmButton className="drawer-btn" disabled={busy} confirmText={`确认删除「${doc.title}」`} onConfirm={() => void corpusAction(doc, "delete")}>删除</ConfirmButton></div>{detail && <CorpusDigestCard doc={doc} detail={detail} />}</article>; })}
{playing && <NovelPlayDialog docId={playing.id} title={playing.title} onClose={() => setPlaying(null)} />}</div>; }
