import type { TurnDiagnosticStage, TurnDiagnosticView, TurnDiagnosticsResponse } from "../types.ts";

const DIAGNOSTIC_STATUS: Record<string, string> = { success: "成功", degraded: "降级", skipped: "跳过", reused: "复用", failed: "失败", committed: "已提交", rejected: "被拒绝", pending: "待确认", stable: "稳定", unavailable: "不可用", approved: "审计通过" };

function scalar(value: unknown): string { return typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? String(value) : ""; }
function StageCard({ stage }: { stage: TurnDiagnosticStage }) {
 const rows = Object.entries(stage.details ?? {}).flatMap(([key, value]) => Array.isArray(value) ? (value.length ? [[key, value.join("、")] as [string,string]] : []) : (scalar(value) ? [[key, scalar(value)] as [string,string]] : []));
 return <article className={`diagnostic-stage ${stage.status}`}><header><span className={`diagnostic-dot ${stage.status}`} /><strong>{stage.label}</strong><b>{DIAGNOSTIC_STATUS[stage.status] || stage.status}</b></header><p>{stage.summary}</p>{rows.length > 0 && <details><summary>查看结构化工件</summary><dl>{rows.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></details>}</article>;
}
function Turn({ turn }: { turn: TurnDiagnosticView }) {
 const workflow = turn.artifacts.workflow ?? {};
 return <article className="diagnostic-turn"><header className="diagnostic-turn-head"><div><span>TURN · {turn.entryId.slice(0, 12)}</span><h3>本拍演出诊断</h3></div><small>{turn.narrativeChars} 字正文 · {turn.curtainChars} 字格式</small></header><div className="diagnostic-metrics"><span>思考 {turn.timeline.thinking} 段</span><span>工具 {turn.timeline.tools} 组</span><span>正文 {turn.timeline.text} 段</span><span>稿件 {scalar(workflow.appends) || "0"} 段</span><span>拒收 {scalar(workflow.appendRejects) || "0"}</span><span>耗时 {workflow.durationMs ? `${Math.round(Number(workflow.durationMs) / 100) / 10}s` : "—"}</span></div><div className="diagnostic-stages">{turn.stages.map((stage) => <StageCard key={stage.id} stage={stage} />)}</div>{turn.artifacts.commits.length > 0 && <details className="diagnostic-commits"><summary>分支提交记录 · {turn.artifacts.commits.length}</summary>{turn.artifacts.commits.map((commit, index) => <div key={`${commit.type}-${index}`}><strong>{commit.type}</strong><span className={commit.status}>{commit.status ? DIAGNOSTIC_STATUS[commit.status] : "已记录"}</span><p>{commit.summary}</p></div>)}</details>}{turn.artifacts.curtain && <details className="diagnostic-commits"><summary>独立谢幕格式原文{turn.artifacts.curtainTruncated ? "（已截断）" : ""}</summary><pre>{turn.artifacts.curtain}</pre></details>}{turn.artifacts.patchAudit && turn.artifacts.patchAudit.length > 0 && <details className="diagnostic-commits"><summary>账本修改审计 · {turn.artifacts.patchAudit.length}</summary><pre>{JSON.stringify(turn.artifacts.patchAudit, null, 2)}</pre></details>}</article>;
}
export function DiagnosticsModule({ diagnostics, loading, error, onReload }: { diagnostics: TurnDiagnosticsResponse | null; loading: boolean; error: string; onReload: () => void }) {
 return <div className="planning-page diagnostics-page"><div className="planning-page-note"><strong>这是执行诊断，不是第二套剧情状态。</strong> 这里展示当前分支已有的拍前工件、主演工作流、门禁结果和拍后提交；模型秘密与隐藏推理不在此页面展开。</div><div className="diagnostic-toolbar"><span>{diagnostics?.turns.length ?? 0} 拍可查看</span><button className="drawer-btn" onClick={onReload} disabled={loading}>{loading ? "刷新中…" : "刷新诊断"}</button></div>{error && <div className="panel-error planning-error">{error}</div>}{loading && !diagnostics && <div className="planning-empty">正在读取本拍工件…</div>}{!loading && diagnostics?.turns.length === 0 && <div className="planning-empty">当前分支还没有可诊断的角色回复。</div>}{diagnostics?.turns.map((turn) => <Turn key={turn.entryId} turn={turn} />)}</div>;
}
